[package]
name = "tefi-oracle"
version = "0.2.0"
authors = ["Terraform Labs, PTE."]
edition = "2018"
description = "Common Orai oracle types"
license = "Apache-2.0"
repository = "https://github.com/oraichain/oracle-hub.git"


[features]
internal = []

[dependencies]
cosmwasm-std = { version = "1.1.9" }
thiserror = { version = "1.0.23" }
cosmwasm-schema = { version = "1.1.9" }
